[package]
name = "sc-executor-wasmtime"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
log = "0.4.8"
wasmi = "0.6.2"
parity-wasm = "0.41.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
take_mut = "0.2.2"
sc-executor-common = { version = "2.0.0", path = "../common" }
sp-wasm-interface = { version = "2.0.0", path = "../../../primitives/wasm-interface" }
sp-runtime-interface = { version = "2.0.0", path = "../../../primitives/runtime-interface" }
sp-core = { version = "2.0.0", path = "../../../primitives/core" }
sp-externalities = { version = "2.0.0", path = "../../../primitives/externalities" }

wasmtime = "0.9"

[dev-dependencies]
assert_matches = "1.3.0"
