[package]
name = "sc-browser"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Tools for creating a browser light-client"
edition = "2018"

[dependencies]
futures = "0.3"
futures01 = { package = "futures", version = "0.1.29" }
log = "0.4.8"
libp2p = { version = "0.13.1", default-features = false }
console_error_panic_hook = "0.1.1"
console_log = "0.1.2"
js-sys = "0.3.22"
wasm-bindgen = "0.2.55"
wasm-bindgen-futures = "0.4.5"
kvdb-web = "0.1.1"
service = { package = "sc-service", path = "../service", default-features = false }
network = { package = "sc-network", path = "../network" }
chain-spec = { package = "sc-chain-spec", path = "../chain-spec" }

# Imported just for the `no_cc` feature
clear_on_drop = { version = "0.2.3", features = ["no_cc"] }
# Imported just for the `wasm-bindgen` feature
rand6 = { package = "rand", version = "0.6", features = ["wasm-bindgen"] }
rand = { version = "0.7", features = ["wasm-bindgen"] }
